// // Generated by CoffeeScript 2.4.1
// // (function() {
//   // terminal colors
//   // var bgize, style;

//   // style = require('ansi-styles');
//   import * as style from 'ansi-styles'

//   function  bgize (color) {
//     return 'bg' + color[0].toUpperCase() + color.slice(1);
//   };

// export const colorUtil= {
//     foreground: function(color) {
//       switch (color) {
//         case 'none':
//           return style.color.close;
//         default:
//           if (color in style.color) {
//             return style.color[color].open;
//           }
//       }
//       return '';
//     },
//     background: function(color) {
//       var bgColor;
//       switch (color) {
//         case 'none':
//           return style.bgColor.close;
//         default:
//           bgColor = bgize(color);
//           if (bgColor in style.bgColor) {
//             return style.bgColor[bgColor].open;
//           }
//       }
//       return '';
//     }
//   }

// // }).call(this);
