// // Generated by CoffeeScript 2.4.1
//   // choose a color
// export function chooseColor({left, up, right, down}) {
//     var background, base, base1, color, colors, count, foreground, i, len, max, maxes, name, name1, ref, ref1, ref2;
//     if (left == null) {
//       left = {};
//     }
//     if (up == null) {
//       up = {};
//     }
//     if (right == null) {
//       right = {};
//     }
//     if (down == null) {
//       down = {};
//     }
//     if (left.foreground == null) {
//       left.foreground = 'none';
//     }
//     if (up.foreground == null) {
//       up.foreground = 'none';
//     }
//     if (right.foreground == null) {
//       right.foreground = 'none';
//     }
//     if (down.foreground == null) {
//       down.foreground = 'none';
//     }
//     if (left.background == null) {
//       left.background = 'none';
//     }
//     if (up.background == null) {
//       up.background = 'none';
//     }
//     if (right.background == null) {
//       right.background = 'none';
//     }
//     if (down.background == null) {
//       down.background = 'none';
//     }
//     colors = {
//       foreground: {},
//       background: {}
//     };
//     ref = [left, up, right, down];
//     for (i = 0, len = ref.length; i < len; i++) {
//       color = ref[i];
//       if (color.foreground !== 'none') {
//         if ((base = colors.foreground)[name = color.foreground] == null) {
//           base[name] = 0;
//         }
//         colors.foreground[color.foreground] += 1;
//       }
//       if (color.background !== 'none') {
//         if ((base1 = colors.background)[name1 = color.background] == null) {
//           base1[name1] = 0;
//         }
//         colors.background[color.background] += 1;
//       }
//     }
//     max = {
//       foreground: 0,
//       background: 0
//     };
//     maxes = {
//       foreground: [],
//       background: []
//     };
//     ref1 = colors.foreground;
//     for (color in ref1) {
//       count = ref1[color];
//       if (!(color !== 'none')) {
//         continue;
//       }
//       if (count > max.foreground) {
//         max.foreground = count;
//         maxes.foreground = [color];
//       }
//       if (count === max.foreground) {
//         maxes.foreground.push(color);
//       }
//     }
//     ref2 = colors.background;
//     for (color in ref2) {
//       count = ref2[color];
//       if (!(color !== 'none')) {
//         continue;
//       }
//       if (count > max.background) {
//         max.background = count;
//         maxes.background = [color];
//       }
//       if (count === max.background) {
//         maxes.background.push(color);
//       }
//     }
//     foreground = 'none';
//     background = 'none';
//     if (maxes.foreground.length > 0) {
//       foreground = maxes.foreground[0];
//     }
//     if (maxes.background.length > 0) {
//       background = maxes.background[0];
//     }
//     return {foreground, background};
//   };

// // }).call(this);
